# ABB/CRB15000

joint_limit:
  joint_1:
    has_position_limit: true
    has_velocity_limit: true
    has_effort_limit: true
    has_acceleration_limit: false
    min_position: -3.141592654
    max_position: 3.141592654
    max_velocity: 3.141592654
    max_effort: 150

  joint_2:
    has_position_limit: true
    has_velocity_limit: true
    has_effort_limit: true
    has_acceleration_limit: false
    min_position: -3.141592654
    max_position: 3.141592654
    max_velocity: 3.141592654
    max_effort: 150

  joint_3:
    has_position_limit: true
    has_velocity_limit: true
    has_effort_limit: true
    has_acceleration_limit: false
    min_position: -3.926990817
    max_position: 1.483529864
    max_velocity: 3.141592654
    max_effort: 150

  joint_4:
    has_position_limit: true
    has_velocity_limit: true
    has_effort_limit: true
    has_acceleration_limit: false
    min_position: -3.141592654
    max_position: 3.141592654
    max_velocity: 3.141592654
    max_effort: 30

  joint_5:
    has_position_limit: true
    has_velocity_limit: true
    has_effort_limit: true
    has_acceleration_limit: false
    min_position: -3.141592654
    max_position: 3.141592654
    max_velocity: 3.141592654
    max_effort: 30

  joint_6:
    has_position_limit: true
    has_velocity_limit: true
    has_effort_limit: true
    has_acceleration_limit: false
    min_position: -4.71238898
    max_position: 4.71238898
    max_velocity: 3.141592654
    max_effort: 30